### ISSUE TITLE
Installation location?

### ISSUE THREAD

**Issue by crashzk** [NickFox007/LuaHudcoreCS2#1]
Should I install this script inside the CSGO folder?

In this case, I'm trying to run it together with [LuaAdvertCS2](https://github.com/NickFox007/LuaAdvertCS2)

**Comment by NickFox007** [comment]
Path: Counter-Strike Global Offensive\game\csgo\scripts\vscripts

**Comment by crashzk** [comment]
I installed it but without success, the script doesn't work.

https://github.com/NickFox007/LuaAdvertCS2/issues/1
